### ISSUE TITLE
Incorrect path separators on Windows

### ISSUE THREAD

**Issue by alumni** [licg9999/transpile-webpack-plugin#38]
webpack.config.js:
```js
config.plugins.push(new TranspilePlugin({ extentionMapping: { '.ts': '.js' } }))
```
main.ts:
```ts
import './some-file'; // also .ts
...
```

If the build is done on Windows, the generated output would contain Windows path separators. This is not correct since node module paths should always use `/`.

main.js (on Windows):
```js
__webpack_require__(".\\some-file.js");
```

**Comment by licg9999** [comment]
Hey @alumni, nice to hear from you.

This does cause some problem. If files are transpiled on windows but run on unix, those files would break. Let me fix it.

**Comment by alumni** [comment]
I was thinking to use `path.posix` instead of just `path` in `TranspileWebpackPlugin.evaluateBundleRelPath`. I haven't tried it yet, but I can try it later and submit a PR if you'd like.

_Later edit:_ in `TranspileWebpackPlugin.collectEntryDepsRecursively`:
```diff
-const entryResourcePath = entryMod.resourceResolveData?.path;
+const entryResourcePath = entryMod.resourceResolveData?.path.replaceAll(path.sep, '/');
```

**Comment by licg9999** [comment]
Yeah, surely love to receive pull requests. But, as I started looking into this problem, I found an awkward mistake I made, which is that my e2e tests didn't get executed in the win32 CI job. As a result, I didn't get reminded of problems on win32. This test matching problem is related to https://github.com/facebook/jest/issues/7914 and I'm going to use `testRegex` to avoid the  matching problem in `testMatch`:

![FastStoneEditor1](https://user-images.githubusercontent.com/8203034/231949020-ce434fa2-91b8-4936-a27c-da02f6c8706b.jpg)

Your idea of the fix looks great and I'm working on https://github.com/licg9999/transpile-webpack-plugin/pull/39 in the similar way to make it real along with the fix for the CI problem.

**Comment by licg9999** [comment]
Hey @alumni, I just released a new version which is `1.1.2`, would you try it? If you meet any problems again, just reach out to me. 🤗

**Comment by alumni** [comment]
Hi @licg9999, I can confirm it's fixed now. Thanks!

**Comment by licg9999** [comment]
You're welcome. Going to close this issue. Good day.
